# Generated by Django 4.1.5 on 2023-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data_for_VaR",
            fields=[
                ("Data_id", models.IntegerField(primary_key=True, serialize=False)),
                ("period", models.IntegerField()),
                ("Time", models.IntegerField()),
                ("InitialInvestment", models.FloatField()),
                ("stock_list", models.CharField(max_length=500)),
                ("portfolio_weights_str", models.CharField(max_length=500)),
            ],
        ),
    ]
