# Generated by Django 4.1.5 on 2023-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_for_var",
            name="Data_id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
