# Generated by Django 4.1.5 on 2023-02-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_data_for_var_data_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_for_var",
            name="confidence_level",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
