# Generated by Django 4.1.5 on 2023-02-28 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_data_for_var_confidence_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_for_var",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
