# Generated by Django 4.1.5 on 2023-03-28 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_data_for_var_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_for_Option_VaR",
            fields=[
                (
                    "Data_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("stock_list", models.CharField(max_length=500)),
                ("option_type_list", models.CharField(max_length=500)),
                ("strike_price_list_str", models.CharField(max_length=500)),
                ("expiration_date_list_str", models.CharField(max_length=500)),
                ("portfolio_weights_str", models.CharField(max_length=500)),
                ("risk_free_rate", models.FloatField()),
                ("confidence_level", models.FloatField()),
                ("number_of_options_list_str", models.CharField(max_length=500)),
            ],
        ),
    ]
